@startuml us10-level3_processes
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : POST /connectors
activate BE

BE -> DB : insert new connector
activate DB

DB -> BE : success
deactivate DB

<-- BE : 201 Created
deactivate BE

@enduml