@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor ADM as "Administrator"
box "<<system (C4>>\nVisualization"<<center>>
  participant CMP as "UI Component" <<component (C4)>>
  participant MOD as "Module" <<component (C4)>>
  participant SRV as "Service" <<component (C4)>>
  participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nMD Management" <<center>>#LightYellow
  participant MDM as "MD Management" <<component (C4)>>
end box

activate ADM

ADM -> CMP : asks to list new user's requests
activate CMP
CMP -> MOD : list new user's requests
activate MOD
MOD -> SRV : list new user's requests
activate SRV
SRV -> HTTP : get('/requests')
activate HTTP

HTTP -> MDM : GET /requests
activate MDM
MDM --> HTTP : 200 (OK)
deactivate MDM
HTTP --> SRV : requests
deactivate HTTP
SRV --> MOD : requests
deactivate SRV
MOD --> CMP : requests
deactivate MOD
CMP --> ADM : requests
deactivate CMP

alt approves request

ADM -> CMP : approves user request
activate CMP
CMP -> MOD : approves user request
activate MOD
MOD -> SRV : approves user request
activate SRV
SRV -> HTTP : patch('/users/:id/accept')
activate HTTP
HTTP -> MDM : PATCH /users/:id/accept
activate MDM
MDM --> HTTP : 204 (No Content)
deactivate MDM
HTTP --> SRV 
deactivate HTTP
SRV --> MOD
deactivate SRV
MOD --> CMP
deactivate MOD
CMP --> ADM
deactivate CMP

else rejects request

ADM -> CMP : rejects user request
activate CMP
CMP -> MOD : rejects user request
activate MOD
MOD -> SRV : rejects user request
activate SRV
SRV -> HTTP : patch('/users/:id/reject')
activate HTTP
HTTP -> MDM : PATCH /users/:id/reject
activate MDM
MDM --> HTTP : 204 (No Content)
deactivate MDM
HTTP --> SRV
deactivate HTTP
SRV --> MOD
deactivate SRV
MOD --> CMP
deactivate MOD
CMP --> ADM
deactivate CMP

end

deactivate ADM

@enduml
