@startuml process-view
autonumber
actor TM as "User"
participant UI as "Visualization" <<system (C4)>>
participant MDD as "MDD" <<system (C4)>>
participant TMD as "Tasks Master Data" <<system (C4)>>
participant P as "Planning" <<system (C4)>>

activate TM

TM -> UI : requests a new request
activate UI


alt request is surveillance then

  UI -> MDD : POST /task-requests/surveillance
  activate MDD

  MDD -> TMD : POST /requests/surveillances
  activate TMD
  deactivate MDD
  deactivate TMD

else request is pickAndDelivery then

  UI -> MDD : POST /task-requests/surveillance
  activate MDD

  MDD -> TMD : POST /requests/pick-and-delivery
  activate TMD
  deactivate TMD
end


MDD --> UI : 201 (returns the request)
deactivate MDD

TM <-- UI : 201 (returns the request)
deactivate UI

deactivate TM

@enduml

