@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"
box "<<system (C4>>\nVisualization"<<center>>
  participant CMP as "UI Component" <<component (C4)>>
  participant MOD as "Module" <<component (C4)>>
  participant SRV as "Service" <<component (C4)>>
  participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nMD Management" <<center>>#LightYellow
  participant MDM as "MD Management" <<component (C4)>>
end box

activate CM

CM -> CMP : asks to edit a building
activate CMP

CM <-- CMP : asks for building data (name,description,max dimensions)
deactivate CMP

CM -> CMP : inputs required data
activate CMP
CMP -> MOD : updates a building
activate MOD
MOD -> MOD : validates data
activate MOD
deactivate MOD
MOD -> SRV : updates a building
activate SRV
SRV -> HTTP : put('/buildings/:buildingCode')

activate HTTP

HTTP -> MDM : put /buildings
activate MDM
MDM --> HTTP : 200 (OK)
deactivate MDM

HTTP --> SRV : updatedBuilding
deactivate HTTP

SRV --> MOD : updatedBuilding
deactivate SRV
MOD --> CMP : updatedBuilding
deactivate MOD

CM <-- CMP : returns confirmation message
deactivate CMP


deactivate CM

@enduml
