version: "3.8"

services:
  database:
    image: mysql:latest
    container_name: mdtasks-mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: mdtasks
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
