@startuml implementation-view

package "RobDroneGo System" {
  
  folder "Visualization" as V {
  }

  folder "MD Management" as MDM {
  }

  folder "Planning" as P {
  }

  folder "MD Tasks" as MDT {
  }
}


MDM <.. V
P <.. MDM
MDM <.. P

MDT <.. MDM
P <. MDT

@enduml
