@startuml implementation-view

package "RobDroneGo System" {
  
  folder "Visualization" as V {
  }

  folder "MD Management" as MDM {
  }

  folder "Planning" as P {
  }
}


MDM <.. V
P <.. MDM

@enduml
