@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : POST /:buildingCode/floors
activate BE

BE -> DB : insert new floor
activate DB

DB -> BE : success
deactivate DB

<-- BE : 201 Created
deactivate BE

@enduml
