@startuml process-view
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : asks to list floors with connectors to other buildings
activate SYS

CM <-- SYS : returns the list
deactivate SYS


deactivate CM

@enduml
