@startuml process-view
autonumber

participant SYS as "MD Management" <<system (C4)>>


?o-> SYS : GET /elevators/:buildingCode
activate SYS

SYS -> SYS : listElevator(building)
<-- SYS : 200 OK (elevator JSON)
deactivate SYS

@enduml
