@startuml process-view
autonumber
participant SYS as "MD Devices" <<system (C4)>>


?o-> SYS : POST /buildings
activate SYS

SYS -> SYS : createBuilding(building)
<-- SYS : 201 Created
deactivate SYS

@enduml
