@startuml us11-level1_processes
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : wants to edit a passage
activate SYS

CM <- SYS : asks for the new passage data
deactivate SYS

CM -> SYS : inserts the data
activate SYS

CM <- SYS : returns confirmation message
deactivate SYS

deactivate CM

@enduml
