@startuml us08-level3_processes
autonumber

participant BE as "Backend"
participant DB as "Database"

?o-> BE : GET /floors?buildingCode={buildingCode}&filter=connectors
activate BE

BE -> DB : get floors with connectors
activate DB

BE <-- DB : floors
deactivate DB

<-- BE : 200 OK
deactivate BE

@enduml
