@startuml process-view
autonumber

actor CM as "Campus Manager"
participant UI as "Visualization" <<system (C4)>>
participant MDD as "MDD" <<system (C4)>>
participant P as "Planning" <<system (C4)>>


activate CM

CM -> UI : asks to create a new room
activate UI

UI -> MDD : POST /buildings/:building/floors/:floor/rooms
activate MDD
MDD --> UI : 201 (room)
deactivate MDD

CM <-- UI : returns room
deactivate UI

deactivate CM

@enduml

