@startuml us08-level2_processes
autonumber

participant SYS as "MD Management" <<system (C4)>>

?o-> SYS : GET /floors?buildingCode={buildingCode}&filter=connectors
activate SYS

SYS -> SYS : listFloorsWithConnectors(building)

<-- SYS : 200 OK {list of floors as JSON}
deactivate SYS

@enduml
