@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor ADM as "Administrator"
box "<<system (C4>>\nVisualization"<<center>>
  participant CMP as "UI Component" <<component (C4)>>
  participant MOD as "Module" <<component (C4)>>
  participant SRV as "Service" <<component (C4)>>
  participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<container (C4)>>\nMD Management" <<center>>#LightYellow
  participant ROUTE as ":Route"
  participant CTRLMDD as ":Controller"
  participant SVCMDD as ":RequestService"
  participant USVCMDD as ":UserService"
  participant HTTPMD as ":HTTP"
end box

box "<<container (C4)>>\nMD Tasks" <<center>>#LightBlue
  participant MDTCTRL as ":Controller"
  participant MDTSRV as ":Service"
  participant MDTDTO as ":requestDTO"
  participant MDTREPO as ":Repo"
end box

activate ADM

ADM -> CMP : selects filter by state
activate CMP

CMP -> ADM : states options 
deactivate CMP

ADM -> CMP : selects state options
activate CMP
CMP -> MOD : list requests by state
activate MOD
MOD -> SRV : getAllRequests(state, value)
activate SRV
SRV -> HTTP : get('/task-requests?filter=state&value=value')
activate HTTP

HTTP -> ROUTE : GET /task-requests?filter=state&value=value
activate ROUTE
ROUTE -> CTRLMDD : getTaskRequests()
activate CTRLMDD

CTRLMDD -> SVCMDD : getTaskRequests(filter, value)
activate SVCMDD

SVCMDD -> HTTPMD : getTaskRequests(filter, value)
activate HTTPMD

HTTPMD -> MDTCTRL : GET /Request?filter=state&value=value
activate MDTCTRL

MDTCTRL -> MDTSRV : GetRequestsByState(value)
activate MDTSRV

MDTSRV -> MDTREPO : GetRequestsByState(value)
activate MDTREPO


MDTREPO --> MDTSRV : requestsList
deactivate MDTDTO
deactivate MDTREPO

loop for each request in requestsList
MDTSRV --> MDTDTO** : createDTO(reqDTO)
end loop


MDTSRV --> MDTCTRL : reqDtoList
deactivate MDTSRV

MDTCTRL --> HTTPMD : 200 (OK)
deactivate MDTCTRL

HTTPMD --> SVCMDD : reqDtoList
deactivate HTTPMD

loop for each request in reqDtoList
SVCMDD -> USVCMDD : getUserById(request.userId)
activate USVCMDD
USVCMDD --> SVCMDD : user
deactivate USVCMDD
end loop

SVCMDD --> CTRLMDD : reqDtoList
deactivate SVCMDD

CTRLMDD --> ROUTE : reqDtoList
deactivate CTRLMDD
ROUTE --> HTTP : 200 (OK)
deactivate ROUTE
HTTP --> SRV : requests
deactivate HTTP
SRV --> MOD : requests
deactivate SRV
MOD --> CMP : requests
deactivate MOD
CMP --> ADM : requests
deactivate CMP

deactivate ADM

@enduml
