@startuml us11-level3_processes
autonumber
participant MD as "MD"
participant DB as "DB"

?o-> MD : PATCH /connectors
activate MD

MD -> DB : updates connector
activate DB

DB -> MD : success
deactivate DB

<-- MD : 200 Created
deactivate MD

@enduml