@startuml process-view
autonumber
box "<<container (C4)>>\nMD Management" <<center>>#LightGreen
  participant ROUTE as ":Route"
  participant CTRLMDD as ":Controller"
end box

box "<<container (C4)>>\nMD Tasks" <<center>>#LightBlue
  participant MDTCTRL as ":Controller"
  participant MDTSRV as ":Service"
  participant MDTDTO as "dto:requestDTO"
  participant MDTREPO as ":Repo"
  participant BUILD as "request:Request"
end box

?o-> ROUTE : POST /requests
activate ROUTE

ROUTE -> CTRLMDD : create(request)
activate CTRLMDD

CTRLMDD -> MDTCTRL : create(requestDTO)
activate MDTCTRL

MDTCTRL -> MDTSRV : create(requestDTO)
activate MDTSRV

MDTSRV -> MDTREPO : create(requestDTO)
activate MDTREPO

MDTREPO -> BUILD** : create
deactivate MDTDTO

MDTREPO --> MDTDTO** : createDTO(reqDTO)
activate MDTDTO

MDTDTO --> MDTSRV : sucess(reqDTO)
deactivate MDTDTO
deactivate MDTREPO

MDTSRV --> MDTCTRL : sucess(reqDTO)
deactivate MDTSRV

MDTCTRL --> CTRLMDD : sucess(reqDTO)
deactivate MDTCTRL

CTRLMDD --> ROUTE : sucess(reqDTO)
deactivate CTRLMDD
<-- ROUTE : 201 OK
deactivate ROUTE

@enduml
