@startuml process-view
autonumber

box "<<container (C4)>>\nMD Tasks" <<center>>#LightBlue
  participant ROUTE as ":Route"
  participant MDTCTRL as ":Controller"
  participant MDTSRV as ":Service"
  participant MDTDTO as "dto:requestDTO"
  participant MDTREPO as ":Repo"
  participant BUILD as "request:Request"
end box

?o-> ROUTE : POST /requests/surveillance
activate ROUTE

ROUTE -> MDTCTRL : create(requestSurveillance)
activate MDTCTRL

MDTCTRL -> MDTSRV : create(requestSurveillance)
activate MDTSRV

MDTSRV -> MDTREPO : create(requestSurveillance)
activate MDTREPO

MDTREPO -> BUILD** : create

MDTREPO --> MDTSRV : request

MDTSRV --> MDTDTO** : create(reqDTO)
deactivate MDTDTO
deactivate MDTREPO

MDTSRV --> MDTCTRL : sucess(reqDTO)
deactivate MDTSRV

MDTCTRL --> ROUTE : sucess(reqDTO)
deactivate MDTCTRL
<-- ROUTE : 201 OK
deactivate ROUTE

@enduml
