@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"
box "<<system (C4>>\nVisualization"<<center>>
  participant CMP as "UI Component" <<component (C4)>>
  participant MOD as "Module" <<component (C4)>>
  participant SRV as "Service" <<component (C4)>>
  participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nMD Management" <<center>>#LightYellow
  participant MDM as "MD Management" <<component (C4)>>
end box

activate CM

CM -> CMP : asks to edit an elevator
activate CMP

CMP -> MOD : get elevator for building
activate MOD
MOD -> SRV : get elevator for building
activate SRV
SRV -> HTTP : get('/buildings/:id/elevators')
activate HTTP
HTTP -> MDM : GET /buildings/:id/elevators
MDM --> HTTP : 200 (elevator)
HTTP --> SRV : elevator
deactivate HTTP
SRV --> MOD : elevator
deactivate SRV
MOD --> CMP : elevator
deactivate MOD

CM <-- CMP : shows elevator data
deactivate CMP

CM -> CMP : gives new elevator data (brand,serial number,description,floors)
activate CMP
CMP -> MOD : edit building elevator
activate MOD
MOD -> MOD : validates data
activate MOD
deactivate MOD
MOD -> SRV : edit an elevator
activate SRV
SRV -> HTTP : put('/buildings/:id/elevators')

activate HTTP

HTTP -> MDM : PUT /buildings/:id/elevators
activate MDM
MDM --> HTTP : 200 (OK)
deactivate MDM

HTTP --> SRV : newElevator
deactivate HTTP

SRV --> MOD : newElevator
deactivate SRV
MOD --> CMP : newElevator
deactivate MOD

CM <-- CMP : returns confirmation message
deactivate CMP


deactivate CM

@enduml
