@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE :  PATCH /devices
activate BE

BE -> DB : get device
activate DB
DB --> BE : device
deactivate DB

BE -> BE : inhibit device
activate BE
deactivate BE
BE -> DB : update device
activate DB
DB --> BE : floor
deactivate DB

<-- BE : 200 OK
deactivate BE

@enduml
