@startuml US4004_SSD
autonumber

actor CM as "Campus Manager"
actor System as "System"

activate CM
activate System

CM -> System : wants to create a building

note left: POST

deactivate System
deactivate CM


@enduml
