@startuml us08-220_ssd
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : wants to create a building
activate SYS

CM <- SYS : asks for the building name
deactivate SYS

CM -> SYS : types the building name
activate SYS

CM <- SYS : returns confirmation message
deactivate SYS

deactivate CM

@enduml
