@startuml process-view
autonumber
actor FM as "Fleet Manager"
participant UI as "Visualization" <<system (C4)>>
participant MDD as "MDD" <<system (C4)>>
participant P as "Planning" <<system (C4)>>

activate FM

FM -> UI : asks to list all robots
activate UI

UI -> MDD : GET /devices/robots
activate MDD
MDD --> UI : 200 (robots)
deactivate MDD

FM <-- UI : returns all robots
deactivate UI


deactivate FM

@enduml
