@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : POST /devices
activate BE

BE -> DB : insert new device
activate DB

DB -> BE : success
deactivate DB

<-- BE : 201 Created
deactivate BE

@enduml
