@startuml process-view
autonumber
participant route as ":DeviceRoute"
participant controller as ":DeviceController"
participant service as ":DeviceService"
participant device as ":device:Device"
participant device_repo as ":DeviceRepo"
participant map as ":DeviceMap"
participant dto as ":deviceDTO:IDeviceDTO"

?o-> route : POST /devices
activate route
route -> controller : createDevice(deviceDTO)
activate controller
controller -> service : createDevice(deviceDTO)
activate service
service -> device** : createDevice(deviceDTO)
service -> device_repo : save(device)
activate device_repo
deactivate device_repo
service -> map : toDto(device)
activate map
map -> dto** : create()
deactivate map
service --> controller : device
deactivate service
controller --> route : device
deactivate controller
<-- route : 201 Created (device JSON)
deactivate route

@enduml
