@startuml process-view
autonumber

participant SYS as "MD Management" <<system (C4)>>


?o-> SYS : GET /devices/robots/:taskId
activate SYS

SYS -> SYS : getRobots(taskId)
<-- SYS : 200 OK (list robots JSON)
deactivate SYS

@enduml
