@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : PUT /:buildingCode/floors/:floorCode
activate BE

BE -> DB : get floor
activate DB
DB --> BE : floor
deactivate DB

BE -> BE : edit floor
activate BE
deactivate BE
BE -> DB : update floor
activate DB
DB --> BE : floor
deactivate DB

<-- BE : 200 OK
deactivate BE

@enduml
