@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"

box "«container (C4)»\nVisualization" <<center>>
  participant C as "UI Component" <<component>>
  participant M as "Module" <<component>>
  participant SVC as "Service" <<component>>
  participant H as "HTTP" <<component>>
end box

box "«container (C4)»\n MD Management " <<center>>#LightYellow
  participant ROUTE as "Route" <<component>>
end box

activate CM

CM -> C : wants to edit a connector
activate C

CM <-- C : asks for the floors 1 & 2 codes
deactivate C

CM -> C : inserts the data
activate C

C -> M : updateConnector
activate M

M -> M : validates data
activate M
deactivate M

M -> SVC : updateConnector(code,floor1,floor2)
activate SVC

SVC -> H : patch(url,data)
activate H

H -> ROUTE : PATCH /connectors/{code}\t {data}
activate ROUTE

alt the connector gets updated
  H <-- ROUTE : 200 OK
  deactivate ROUTE

  SVC <-- H : the updated connector
  deactivate H

  M <-- SVC : the updated connector
  deactivate SVC

  C <-- M : success message
  deactivate M

  CM <-- C : informs the success of the operation
else there is a connector between those floors
  activate H
  activate M
  activate SVC
  activate ROUTE

  H <-- ROUTE : 400 Bad Request
  deactivate ROUTE

  SVC <-- H : error
  deactivate H

  M <-- SVC : error
  deactivate SVC

  C <-- M : error
  deactivate M

  CM <-- C : shows error message "A connector exists between those floors."
  deactivate C
end

deactivate CM

@enduml
