@startuml ucd-sprint-a

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Fleet Manager: as Fleet
:Campus Manager: as Campus

left to right direction

rectangle "Campus Managing" as campus {
  usecase "150. Create a building" as createBuilding
  usecase "160. Edit a building information" as editBuilding
  usecase "170. List all buildings" as listBuildings
  usecase "180. List all buildings with given minimum and maximum number of floors" as listBuildingsWithFloors
  usecase "190. Create a floor in a given building" as createFloor
  usecase "200. Edit information of a given floor" as editFloor
  usecase "210. List all floors for a given building " as listFloors
  usecase "220. List all floors with connection to other buildings" as listFloorsWithConnections
  usecase "230. Load a map for a given floor" as loadFloorMap
  usecase "240. Create a connection between 2 floors" as createConnection
  usecase "250. Edit a connection between 2 floors" as editConnection
  usecase "260. List all the connection between 2 buildings" as listBuildingsConnections
  usecase "270. Create an elevator" as createElevator
  usecase "280. Edit an elevator" as editElevator
  usecase "290. List all the elevators for a given building" as listElevators
  usecase "300. List all the floors reachable by elevator for a given building" as listFloorsReachableByElevator
  usecase "310. Create a room in a given floor" as createRoom
}

rectangle "Fleet Managing" as fleet {
  usecase "350. Create a new robot type and assign specific tasks" as createRobotType
  usecase "360. Create a new robot with a given type" as createRobot
  usecase "370. Disable a robot" as disableRobot
  usecase "370. List all robots" as listRobots
  usecase "370. Search robots for a specific designation or task" as searchRobot
}

Campus --> createBuilding
Campus --> editBuilding
Campus --> listBuildings
Campus --> listBuildingsWithFloors
Campus --> createFloor
Campus --> editFloor
Campus --> listFloors
Campus --> listFloorsWithConnections
Campus --> loadFloorMap
Campus --> createConnection
Campus --> editConnection
Campus --> listBuildingsConnections
Campus --> createElevator
Campus --> editElevator
Campus --> listElevators
Campus --> listFloorsReachableByElevator
Campus --> createRoom

Fleet --> createRobotType
Fleet --> createRobot
Fleet --> disableRobot
Fleet --> listRobots
Fleet --> searchRobot

@enduml
