@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : GET /buildings
activate BE

BE -> DB : get all buildings
activate DB
DB --> BE : buildings
deactivate DB

<-- BE : 200 OK
deactivate BE

@enduml
