@startuml process-view
autonumber
actor TM as "Task Manager"
participant UI as "Visualization" <<system (C4)>>
participant TMD as "Tasks Master Data" <<system (C4)>>
participant P as "Planning" <<system (C4)>>
participant MDD as "MDD" <<system (C4)>>

activate TM

TM -> UI : asks to get the sequence of execution of the approved tasks
activate UI

UI -> TMD : GET /requests/sequence
activate TMD
TMD -> P : GET /sequence
activate P
P -> TMD : GET /requests/pick-delivery?status=approved
activate TMD
TMD --> P : GET /requests/pick-delivery?status=approved
deactivate TMD
P -> P : runs algorithm to get the sequence of tasks
activate P
deactivate P
P --> TMD : 200 (sequence of tasks)
deactivate P
TMD --> UI : 200 (sequence of tasks)
deactivate TMD

TM <-- UI : returns the sequence of tasks
deactivate UI

deactivate TM

@enduml

