@startuml process-view
autonumber

actor ADM as "Administrator"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate ADM

ADM -> SYS : asks to create a new user
activate SYS
ADM <-- SYS : asks user's personal data, including his role in the system
deactivate SYS

ADM -> SYS : enters user's personal data
activate SYS

ADM <-- SYS : returns a confirmation message
deactivate SYS

deactivate ADM

@enduml

