@startuml process-view
autonumber

actor ADM as "Administrator"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate ADM

ADM -> SYS : asks to list new user's requests
activate SYS
ADM <-- SYS : lists new user's requests
deactivate SYS

ADM -> SYS : approves or rejects a new user's request
activate SYS

ADM <-- SYS : returns a confirmation message
deactivate SYS

deactivate ADM

@enduml

