@startuml prod-physical-view

node "localhost: ?" as LOCAL {
  component "Browser" as B <<component>> {
    component "UI" as UI <<component>> {
    }
  }
}

node "Server 1: ?" as S1 {
  component "MDManagement" as MDM <<component>> { 
  }
}

node "Server 4: ?" as S4 {
  component "Planning" as P <<component>>  { 
  }
}

node "Server 6: ?" as S6 {
  component "MDTasks" as MDT <<component>>  { 
  }
}

node "Server 3: ?" as S3 {
  database "MongoDB" as DB <<database>> {
  }
}

node "Server 5: ?" as S5 {
  database "MySQL" as MYSQLDB <<database>> {
  }
}

node "Server 2: ?" as S2 {
  component "HTTP Server" as SERV <<component>> { 
  }
  folder "Visualization" as V {
  }
} 

LOCAL -- S1 : http/s
LOCAL --- S2 : http/s
S1 -- DB : tcp
S1 -- S4 : http/s
S6 -- MYSQLDB : tcp
S6 -- S4 : http/s
S6 -- S1 : http/s

@enduml
