@startuml prod-physical-view

node "localhost: ?" as LOCAL {
  component "Browser" as B <<component>> {
    component "UI" as UI <<component>> {
    }
  }
}

node "Server 1: ?" as S1 {
  component "MDManagement" as MDM <<component>> { 
  }
}

node "Server 4: ?" as S4 {
  component "Planning" as P <<component>>  { 
  }
}

node "Server 3: ?" as S3 {
  database "MongoDB" as DB <<database>> {
  }
}

node "Server 2: ?" as S2 {
  component "HTTP Server" as SERV <<component>> { 
  }
  folder "Visualization" as V {
  }
} 

LOCAL -- S1 : http/s
LOCAL -- S2 : http/s
S1 -- DB : tcp/27017
S1 -- S4 : http/s

@enduml
