@startuml process-view
autonumber

actor FM as "Fleet Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate FM

FM -> SYS : asks to inhibit a robot by its code
activate SYS

FM <-- SYS : returns confirmation message
deactivate SYS

deactivate FM

@enduml
