@startuml process-view
autonumber
participant ROUTE as ":ElevatorRoute"
participant CTRL as ":ElevatorController"
participant SRV as ":ElevatorService"
participant BREPO as ":BuildingRepo"
participant MAP as ":ElevatorMap"
participant DTO as ":elevatorDTO:IElevatorDTO"

?o-> SYS : GET buildings/:id/elevators
activate ROUTE

ROUTE -> CTRL : listElevator(buildingCode)
activate CTRL
CTRL -> SRV : listElevator(buildingCode)
activate SRV
SRV -> BREPO : building=findByDomainId(buildingId)
activate BREPO
deactivate BREPO
SRV -> MAP : toDto(buidling.elevator)
activate MAP
MAP -> DTO** : create()
deactivate MAP
SRV --> CTRL : sucess(elevatorDTO)
deactivate SRV
CTRL --> ROUTE : sucess(elevatorDTO)
deactivate CTRL
<-- ROUTE : 200 OK
deactivate ROUTE

@enduml
