@startuml us12-level3_processes
autonumber

participant ROUTE as ":ConnectorRoute"
participant CTRL as ":ConnectorController"
participant SVC as ":ConnectorService"
participant E as ":Connector"
participant REPO as ":ConnectorRepository"
participant CMAP as ":ConnectorMap"
participant DTO as ":ConnectorDTO"

?o-> ROUTE : GET /connectors?building1Code={building1Code}&building1Code={building1Code}
activate ROUTE

  ROUTE -> CTRL : listConnectorsBetweenBuildings(building1Code, building2Code)
  activate CTRL

    CTRL -> SVC : listConnectorsBetweenBuildings(building1Code, building2Code)
    activate SVC

      SVC -> REPO : findByFloorOfBuildings(building1Code, building2Code)
      activate REPO

      REPO --> SVC : Connector[]
      deactivate REPO

      loop for each connector

        SVC -> CMAP : mapToDTO(connector)
        activate CMAP

          CMAP -> DTO : create()
          activate DTO

          DTO --> CMAP : ConnectorDTO
          deactivate DTO

        CMAP --> SVC : ConnectorDTO[]
        deactivate CMAP
      
      end

    CTRL <-- SVC : ConnectorDTO[]
    deactivate SVC

  ROUTE <-- CTRL : FloorDTO[]
  deactivate CTRL
  
<-- ROUTE : 200 OK (list of connectorss as JSON)
deactivate ROUTE

@enduml
