@startuml us12-level3_processes
autonumber

participant BE as "Backend"
participant DB as "Database"

?o-> BE : GET /connectors?building1Code={building1Code}&building2Code={building2Code}
activate BE

BE -> DB : get building floors
activate DB
DB --> BE : floors
deactivate DB

BE -> DB : get connectors between floors
activate DB
DB --> BE : connectors
deactivate DB

<-- BE : 200 OK
deactivate BE

@enduml
