@startuml process-view
autonumber
participant SYS as "MD Management" <<system>>

?o-> SYS : POST /device-models
activate SYS

SYS -> SYS : createDeviceModel(deviceModel)
<-- SYS : 201 Created (Device Model JSON)
deactivate SYS

@enduml
