@startuml implementation-view

component "MD Management" as MDM <<component>> <<container (C4)>> {
  folder Infrastructure as I {
    package Persistence as PERS {}
    package Routes as ROUTE {}
  }

  folder "Interface Adapters" as IA {
    package Controllers as CTRL {}
    package Repositories as REPO {}
  }

  folder "Application Services/Use Case Services" as UC {
    package "App Services" as APP {}
  }

  folder "Entities/Core/Domain" as E {
    package "Aggregates" as AGG {}
    package "Value Objects" as VO {}
    package "Services" as SRV {}
  }
}

ROUTE ..> CTRL
REPO ..> PERS
CTRL ..> APP
REPO ..> APP
APP ..> AGG
APP ..> VO
APP ..> SRV

I ..> IA
IA ..> UC
UC ..> E

@enduml
