@startuml process-view
autonumber

actor User as "User" 
participant SYS as "RobDroneGo System" <<system (C4)>>

activate User

User -> SYS : requests a task 
activate SYS

User <-- SYS : asks for the necessary information
deactivate SYS

User -> SYS : sends the information
activate SYS

User <-- SYS : returns sucess
deactivate SYS

deactivate User

@enduml
