@startuml process-view
autonumber
actor ADM as "Administrator"
participant UI as "Visualization" <<system (C4)>>
participant MMD as "Management Master Data" <<system (C4)>>
participant TMD as "Tasks Master Data" <<system (C4)>>
participant P as "Planning" <<system (C4)>>

activate ADM

ADM -> UI : asks to list new user's requests
activate UI
UI -> MMD : GET /requests
activate MMD
MMD --> UI : 200 (OK)
deactivate MMD

ADM <-- UI : lists new user's requests
deactivate UI

ADM -> UI : approves or rejects a new user's request
activate UI

alt approves request
    UI -> MMD : PATCH /users/{id}/accept
    activate MMD
    MMD --> UI : 204 (No Content)
    deactivate MMD
else rejected
    UI -> MMD : PATCH /users/{id}/reject
    activate MMD
    MMD --> UI : 204 (No Content)
    deactivate MMD
end

ADM <-- UI : returns a confirmation message
deactivate UI

deactivate ADM

@enduml

