@startuml process-view
autonumber
actor TM as "User"
participant UI as "Visualization" <<system (C4)>>
participant MDD as "MDD" <<system (C4)>>
participant TMD as "Tasks Master Data" <<system (C4)>>
participant P as "Planning" <<system (C4)>>

activate TM

alt approves request
  TM -> UI : approves a request
  activate UI

  UI -> MDD : GET /robots?filter=task&value={task_type}
  activate MDD

  UI <-- MDD : 200 OK (robots)
  deactivate MDD

  TM <-- UI : asks to select the robot
  deactivate UI

  UI -> TM : selects the desired robot
  activate UI

  UI -> MDD : PATCH /task-requests/{id}/accept {robotId}
  activate MDD

  MDD -> TMD : PATCH /requests/{id}/accept {robotId}
  activate TMD

  MDD <-- TMD : 200 OK (task request)
  deactivate TMD

  UI <-- MDD : 200 OK (task request)
  deactivate MDD

  TM <-- UI : 200 OK (task request)
  deactivate UI
else rejects request
  UI -> TM : rejects a request
  activate UI

  UI -> MDD : PATCH /task-requests/{id}/reject
  activate MDD

  MDD -> TMD : PATCH /requests/{id}/reject
  activate TMD

  MDD <-- TMD : 200 OK (task request)
  deactivate TMD

  UI <-- MDD : 200 OK (task request)
  deactivate MDD

  TM <-- UI : 200 OK (task request)
  deactivate UI
end

deactivate TM

@enduml
