@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"
box "<<container (C4>>\nVisualization)"<<center>>
  participant CMP as "UI Componente" <<component (C4)>>
    participant CMP as "UI Component" <<component (C4)>>
  participant MOD as "Module" <<component (C4)>>
  participant SRV as "Service" <<component (C4)>>
  participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<container (C4)>>\nMD Management" <<center>>#LightYellow
  participant MDM as "Floor Route" <<component>>
end box

activate CM

CM -> CMP : asks to create a floor
activate CMP

CM <-- CMP : asks for floor data
deactivate CMP

CM -> CMP : inputs required data
activate CMP

CMP -> MOD : create new floor
activate MOD
MOD -> MOD : validate data
activate MOD
deactivate MOD

MOD -> SRV : create new floor
activate SRV
SRV -> HTTP : post(/buildings/:buildingCode/floors)
activate HTTP

HTTP -> MDM : POST /buildings/:buildingCode/floors
activate MDM
MDM --> HTTP : 201 Created
deactivate MDM

HTTP --> SRV : createdFloor
deactivate HTTP

SRV --> MOD : createdFloor
deactivate SRV
MOD --> CMP : createdFloor
deactivate MOD

CM <-- CMP : returns confirmation message
deactivate CMP

deactivate CM

@enduml
