@startuml lv-iv

folder "RobDroneGo" {
  
  folder "Visualization" as PV {
  }

  folder "MD Management" as PMDM {
  }

  folder "Planning" as PP {
  }
}


PMDM <.. PV
PP <.. PMDM

/' ----------------------------------------------------- '/

interface "Admin UI" as AUI
interface "Campus Manager UI" as CUI
interface "Fleet Manager UI" as FUI
interface "Task Manager UI" as TUI
interface "User UI" as UUI

component "RobDroneGo System" <<component>> <<system (C4)>> {
  portin " " as P1

  Interface "API-Management" as API
  Interface "API-Planning" as PAPI
  
  component "Visualization" as V <<component>> <<system (C4)>> {
  }

  component "MD Management" as MDM <<component>> <<system (C4)>> {
  }

  component "Planning" as P <<component>> <<system (C4)>> {
  }
}


V -- P1
MDM -up- API
V --( API
P --( API
P -- PAPI
MDM -up-( PAPI

AUI -- P1
CUI -- P1
FUI -- P1
TUI -- P1
UUI -- P1

PV ..> V : <<manifest>>
PMDM ..> MDM : <<manifest>>
PP ..> P : <<manifest>>

@enduml
