@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : PUT /buildings/:id/elevators
activate BE

BE -> DB : get building
activate DB
DB --> BE : building
deactivate DB

BE -> BE : edit elevator
activate BE
deactivate BE
BE -> DB : update building with new elevator
activate DB
DB --> BE : building
deactivate DB

<-- BE : 200 OK
deactivate BE

@enduml
