@startuml logic-view

interface "Admin UI" as AUI
interface "Campus Manager UI" as CUI
interface "Fleet Manager UI" as FUI
interface "Task Manager UI" as TUI
interface "User UI" as UUI

component "Rob" <<component>> <<system (C4)>> {
  portin " " as P1

  component "Visualization" as V <<component>> <<system (C4)>> {
  }

  component "MD Devices" as MDD <<component>> <<system (C4)>> {
  }
}


V -- P1
MDD -0)- V

AUI -- P1
CUI -- P1
FUI -- P1
TUI -- P1
UUI -- P1

@enduml
