@startuml process-view
autonumber
participant ROUTE as ":ElevatorRoute"
participant CTRL as ":ElevatorController"
participant SRV as ":ElevatorService"
participant ELEV as ":elevator:Elevator"
participant REPO as ":ElevatorRepo"
participant BREPO as ":BuildingRepo"
participant MAP as ":ElevatorMap"
participant BUILD as ":building:Building"
participant PERS as "elevatorPersistence:IElevatorPersistence"
participant MODEL as ":Model<IElevatorPersistence & Document>"
participant NELEV as ":newElevator:Elevator"
participant DTO as ":elevatorDTO:IElevatorDTO"

?o-> ROUTE : POST /elevators
activate ROUTE

ROUTE -> CTRL : createElevator(request)
activate CTRL
CTRL -> SRV : createElevator(elevatorDTO,buildingDTO)
activate SRV
SRV -> BREPO : exists(buildingDTO.code)
activate BREPO
deactivate BREPO
SRV -> ELEV** : create()
SRV -> REPO : save(elevator)
activate REPO
REPO -> MAP : toPersitence(elevator)
activate MAP
deactivate MAP
REPO -> PERS** : create()
REPO -> MODEL : create(elevatorPersistence)
activate MODEL
deactivate MODEL
REPO -> MAP : toDomain(elevatorPersistence)
activate MAP
MAP -> NELEV** : create()
deactivate MAP
REPO --> SRV : newElevator
deactivate REPO
SRV -> BREPO : addElevatorForCode(buildingDTO.code, newElevator)
activate BREPO
BREPO -> BREPO: elevator=findWithCode(buildingDTO.code)
BREPO -> BUILD : setElevator(elevator)
activate BUILD
deactivate BUILD
deactivate BREPO
SRV -> MAP : toDto(newElevator)
activate MAP
MAP -> DTO** : create()
deactivate MAP
SRV --> CTRL : sucess(elevatorDTO)
deactivate SRV
CTRL --> ROUTE : sucess(elevatorDTO)
deactivate CTRL
<-- ROUTE : 201 Created
deactivate ROUTE

@enduml
