@startuml process-view
autonumber
participant ROUTE as ":ElevatorRoute"
participant CTRL as ":ElevatorController"
participant SRV as ":ElevatorService"
participant ELEV as ":elevator:Elevator"
participant FLIST as "floorList:Floor[]"
participant BREPO as ":BuildingRepo"
participant FREPO as ":FloorRepo"
participant MAP as ":ElevatorMap"
participant BUILD as "building:Building"
participant DTO as ":elevatorDTO:IElevatorDTO"

?o-> SYS : POST /buildings/:id/elevators
activate ROUTE

ROUTE -> CTRL : createElevator(elevatorDTO)
activate CTRL
CTRL -> SRV : createElevator(elevatorDTO)
activate SRV
SRV -> BREPO : findByDomainId(elevatorDTO.buildingCode)
activate BREPO
deactivate BREPO
SRV -> FLIST** : create()
note right of FLIST
  we must check if the floorIds all 
  belong to the same building
end note
loop for each floorId in elevatorDTO.floorIds
  SRV -> FREPO : floor=findWithId(floorId)
  activate FREPO
  deactivate FREPO
  SRV -> FLIST : add(floor)
  activate FLIST
  deactivate FLIST
end
SRV -> ELEV** : create()
SRV -> BUILD : addElevator(newElevator)
activate BUILD
deactivate BUILD
SRV -> MAP : toDto(elevator)
activate MAP
MAP -> DTO** : create()
deactivate MAP
SRV --> CTRL : sucess(elevatorDTO)
deactivate SRV
CTRL --> ROUTE : sucess(elevatorDTO)
deactivate CTRL
<-- ROUTE : 201 Created
deactivate ROUTE

@enduml
