@startuml lv-iv

interface "MD API" as API

component "MD Management" as MDM <<component>> <<container (C4)>> {
  portin " " as P1
  portin "Persistence API" as P2

  Interface "Controller API" as CTRL_API
  Interface "Data Model API" as DATA_API


  folder "Frameworks & Drivers Layer" as FDL #80FFFF {
    component "Routing" as ROUTE <<component>> {
    }
    component "Persistence" as PERSISTENCE <<component>> {
    }
  }

  component "Data Model" as DATA <<component>> {
  }
  component "DTO" as DTO <<component>> {
  }

  Interface "App Services API" AS SRV_API
  Interface "DTO API" AS DTO_API
  Interface "Repo API" AS REPO_API
  Interface "Model API" AS MODEL_API
  Interface "Persistence API" AS PERSISTENCE_API

  folder "Interface Adapters Layer" as IAL #80FF80 {
    component "Controller" as CTRL <<component>> {
    }
    component "Repository" as REPO <<component>> {
    }
  }

  folder "Application Business Rules" as ABR #FF8080 {
    component "Application Service" as SRV <<component>> {
    }
  }

  folder "Enterprise Business Rules" as EBR #FFC080 {
    component "Domain Model DDD" as MODEL <<component>> {
    }
  }
}

API -- P1

ROUTE --- P1
PERSISTENCE -- P2

ROUTE --( CTRL_API
CTRL -up- CTRL_API
PERSISTENCE -- PERSISTENCE_API
REPO -up-( PERSISTENCE_API 
PERSISTENCE --( DATA_API 
REPO -up-( DATA_API 
DATA --( DATA_API 

CTRL --( SRV_API
SRV -up-( SRV_API
SRV -up-( DTO_API
CTRL --( DTO_API
DTO --( DTO_API

REPO -- REPO_API
SRV -up-( REPO_API 

SRV --( MODEL_API 
REPO --( MODEL_API 
MODEL -up- MODEL_API 

' ---------------------

component "MD Management" as MDM2 <<component>> <<container (C4)>> {
  folder Infrastructure as I2 {
    folder Persistence as PERS2
    folder Routes as ROUTE2
  }

  folder "Interface Adapters" as IA2 {
    folder Controllers as CTRL2
    folder Repositories as REPO2
  }

  folder "Application Services/Use Case Services" as UC2 {
    folder "App Services" as APP2
  }

  folder "Entities/Core/Domain" as E2 {
    folder "Aggregates" as AGG2 
    folder "Value Objects" as VO2
    folder "Services" as SRV2
  }
}

ROUTE2 .up.> CTRL2
REPO2 .up.> PERS2
CTRL2 .up.> APP2
REPO2 .up.> APP2
APP2 .up.> AGG2
APP2 .up.> VO2
APP2 .up.> SRV2

I2 .up.> IA2
IA2 .up.> UC2
UC2 .up.> E2

I2 .up.> FDL : <<manifest>>
IA2 .up.> IAL : <<manifest>>
UC2 .up.> ABR : <<manifest>>
E2 .up.> EBR : <<manifest>>

@enduml
