@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE : GET  /devices/robots?filter=task&value=taskType
activate BE

BE -> DB : get devices that are robots by taskId
activate DB

DB --> BE : robots
deactivate DB

<--o BE : 200 OK
deactivate BE

@enduml