@startuml process-view
autonumber
participant ROUTE as ":DeviceRoute"
participant CTRL as ":DeviceController"
participant SRV as ":DeviceService"
participant DREPO as ":DevicesRepo"
participant MAP as ":DeviceMap"
participant DTO as ":DeviceDTO:IDeviceDTO"

?o-> ROUTE : GET /devices/:taskId
activate ROUTE

ROUTE -> CTRL : listRobots(taskId)
activate CTRL
CTRL -> SRV : listRobots(taskId)
activate SRV
SRV -> DREPO : robot=findByTaskId(taskId)
activate DREPO
deactivate DREPO
SRV -> MAP : toDto(robot.elevator)
activate MAP
MAP -> DTO** : create()
deactivate MAP
SRV --> CTRL : sucess(robotDTO)
deactivate SRV
CTRL --> ROUTE : sucess(robotDTO)
deactivate CTRL
<-- ROUTE : 200 OK
deactivate ROUTE

@enduml
