@startuml us1210
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : wants to create a room
activate SYS

CM <- SYS : asks for the room data and floor
deactivate SYS

CM -> SYS : inserts the data
activate SYS

CM <- SYS : returns confirmation message
deactivate SYS

deactivate CM

@enduml
