@startuml process-view
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : asks to list floors served by elevator from a given building
activate SYS

CM <-- SYS : returns list of floors
deactivate SYS

deactivate CM

@enduml
