@startuml process-view
autonumber
participant BE as "BE"
participant DB as "DB"

?o-> BE: GET /:building/floors
activate BE

BE -> DB : get floors with building id
activate DB

DB --> BE : floors
deactivate DB

<-- BE: 200 OK
deactivate BE

@enduml