@startuml process-view
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : wants to edit a connector
activate SYS

CM <-- SYS : asks for the floor 1 & floor 2 codes
deactivate SYS

CM -> SYS : inserts the data
activate SYS

alt the connector gets updated
  CM <-- SYS : returns the updated connector
else there is a connector between those floors
  CM <-- SYS : shows error message "A connector exists between those floors."
  deactivate SYS
end

deactivate CM

@enduml
