@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"

box "«container (C4)»\nVisualization" <<center>>
  participant C as "ConnectorComponent" <<component>>
  participant SVC as "ConnectorService" <<component>>
end box

box "«container (C4)»\n MD Management " <<center>>#LightYellow
  participant ROUTE as "ConnectorRoute" <<component>>
end box

activate CM

CM -> C : wants to list floors with connectors to other buildings
activate C

CM <-- C : asks for the connector code, floors 1 & 2 codes
deactivate C

CM -> C : inserts the data
activate C

C -> SVC : createConnector(code,floor1,floor2)
activate SVC

SVC -> ROUTE : POST /connectors {data}
activate ROUTE

alt a new connector is created
  SVC <-- ROUTE : 201 Created
  deactivate ROUTE

  C <-- SVC : the new connector
  deactivate SVC

  CM <-- C : informs the success of the operation
else there is a connector between those floors
  activate SVC
  activate ROUTE

  SVC <-- ROUTE : 400 Bad Request
  deactivate ROUTE

  C <-- SVC : error
  deactivate SVC

  CM <-- C : shows error message "A connector exists between those floors."
  deactivate C
end

deactivate CM

@enduml
