@startuml process-view
autonumber

actor CM as "Campus Manager"
participant SYS as "RobDroneGo System" <<system (C4)>>

activate CM

CM -> SYS : asks to edit an elevator (brand,serial number,description) for a given building
activate SYS
CM <-- SYS : returns confirmation message
deactivate SYS

deactivate CM

@enduml
