@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"
box "<<system (C4>>\nVisualization"<<center>>
  participant CMP as "UI Component" <<component (C4)>>
  participant MOD as "Module" <<component (C4)>>
  participant SRV as "Service" <<component (C4)>>
  participant HTTP as "HTTP" <<component (C4)>>
end box

box "<<system (C4)>>\nMD Management" <<center>>#LightYellow
  participant MDM as "MD Management" <<component (C4)>>
end box

activate CM

CM -> CMP : asks to list a building elevator
activate CMP

CMP -> MOD : get elevator for building
activate MOD
MOD -> SRV : get elevator for building
activate SRV
SRV -> HTTP : get('/buildings/:id/elevators')
activate HTTP
HTTP -> MDM : GET /buildings/:id/elevators
MDM --> HTTP : 200 (elevator)
HTTP --> SRV : elevator
deactivate HTTP
SRV --> MOD : elevator
deactivate SRV
MOD --> CMP : elevator
deactivate MOD

CM <-- CMP : shows elevator data
deactivate CMP

deactivate CM

@enduml
