@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"

box "«container (C4)»\nVisualization" <<center>>
  participant C as "Component" <<component>>
  participant SVC as "Service" <<component>>
  participant H as "HTTP" <<component>>
end box

box "«container (C4)»\n MD Management " <<center>>#LightYellow
  participant ROUTE as "Route" <<component>>
end box

activate CM

CM -> C : wants to create a room in a building floor
activate C

CM <-- C : asks for the name, description, floor code, dimensions & category
deactivate C

CM -> C : inserts the data
activate C

C -> SVC : createRoom(buildingFloor,floorCode,data)
activate SVC

SVC -> H : post(url,data)
activate H

H -> ROUTE : POST /buildings/{buildingCode}/floors/{floorCode}/rooms {data}
activate ROUTE

alt a new room is created
  H <-- ROUTE : 201 Created
  deactivate ROUTE

  SVC <-- H : the new room
  deactivate H

  C <-- SVC : the new room
  deactivate SVC

  CM <-- C : informs the success of the operation
else there is a room with the specified code
  activate H
  activate SVC
  activate ROUTE

  H <-- ROUTE : 400 Bad Request
  deactivate ROUTE

  SVC <-- H : error
  deactivate H

  C <-- SVC : error
  deactivate SVC

  CM <-- C : shows error message "A room with that name exists."
  deactivate C
end

deactivate CM

@enduml
