@startuml process-view
autonumber
skinparam DefaultTextAlignment<<center>> center

actor CM as "Campus Manager"

box "«container (C4)»\nVisualization" <<center>>
  participant C as "UI Component" <<component>>
  participant M as "Module" <<component>>
  participant SVC as "Service" <<component>>
  participant H as "HTTP" <<component>>
end box

box "«container (C4)»\n MD Management " <<center>>#LightYellow
  participant ROUTE as "Route" <<component>>
end box

activate CM

CM -> C : wants to list connectors between 2 buildings
activate C

CM <-- C : asks for the buildings 1 & 2 codes
deactivate C

CM -> C : inserts the data
activate C

C -> M : getConnectorsBetweenBuildings
activate M

M -> SVC : getConnectorsBetweenBuildings(building1,building2)
activate SVC

SVC -> H : get(url)
activate H

H -> ROUTE : GET /connectors?buildingCodes[]={code1}&buildingCodes[]={code2}
activate ROUTE

alt there are connectors between those buildings
  H <-- ROUTE : 200 OK
  deactivate ROUTE

  SVC <-- H : list of connectors
  deactivate H

  M <-- SVC : list of connectors
  deactivate SVC

  C <-- M : list of connectors
  deactivate M

  CM <-- C : shows the list
else a building code does not exist
  activate H
  activate M
  activate SVC
  activate ROUTE

  H <-- ROUTE : 400 Bad Request
  deactivate ROUTE

  SVC <-- H : error
  deactivate H

  M <-- SVC : error
  deactivate SVC

  C <-- M : error
  deactivate M

  CM <-- C : shows error message "One/both buildings does not exist."
else there are not connectors between those buildings
  activate H
  activate M
  activate SVC
  activate ROUTE

  H <-- ROUTE : 200 OK
  deactivate ROUTE

  SVC <-- H : empty list of connectors
  deactivate H

  M <-- SVC : empty list of connectors
  deactivate SVC

  C <-- M : empty list of connectors
  deactivate M

  CM <-- C : shows message "Could not find connectors."
end

deactivate CM

@enduml
