@startuml process-view
autonumber
participant SYS as "MD Management" <<system (C4)>>


?o-> SYS : GET /:building/floors
activate SYS

SYS -> SYS : getFloors()
<-- SYS : 200 OK (List of floors JSON)
deactivate SYS

@enduml
