@startuml process-view
autonumber
participant SYS as "MD Management" <<system (C4)>>


?o-> SYS : POST /buildings/:building/floors/:floor/rooms
activate SYS

SYS -> SYS : createRoom()
<-- SYS : 201 CREATED (new room JSON)
deactivate SYS

@enduml
