name: Deploy MD-Management

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [main]
    paths:
      - "md-management/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: md-management/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Test & Build
        run: |
          # pnpm test
          pnpm build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

      - name: Copy Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "md-management/dist/*,md-management/package.json,md-management/pnpm-lock.yaml"
          target: "~/deploy"
          rm: true

      - name: Deploy Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/md-management
            pnpm i --frozen-lockfile
            export MONGODB_URI="${{ secrets.MONGODB_URI }}" PORT="2224" JWT_SECRET="${{ secrets.JWT_SECRET }}"
            pm2 restart md-management || pm2 start dist/index.js --name md-management
