@startuml process-view
autonumber
participant SYS as "MD Management" <<system>>

?o-> SYS : GET /devices/robots
activate SYS

SYS -> SYS : getRobots()
<-- SYS : 200 OK (list of robots JSON)
deactivate SYS

@enduml
